Repository flutterph/devs, pull requests merged in 2021-02, with the labels that each got.

#5 [BUG] fix asset logo on dashboard page
  lib/features/dashboard/dashboard_page.dart
Labels: #30daysOfFlutter, b: breaking

#6 [bugfix] Fix #3 devs assets not loading
  lib/core/datasource/local/devs_local_datasource.dart
Labels: #30daysOfFlutter, bug

#14 [bugfix] Fix #8 copy CNAME from master
  .github/workflows/deploy.yml
Labels: #30daysOfFlutter, b: breaking

#45 [docs] Add contributing guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation

#34 Add Karlo Barcelona to devs
  assets/data/devs.json
  pubspec.lock
Labels: 1 point

#59 Add Anike Dorgu details
  assets/data/devs.json
Labels: 1 point

#61 "Add Jazzy Bulacito details"
  assets/data/devs.json
Labels: #30daysOfFlutter, 1 point

#66 Added "Kean Allen" on the dev boards
  .gitignore
  assets/data/devs.json
  lib/features/devboard/devs/devs_list.dart
  pubspec.lock
Labels: #30daysOfFlutter, 1 point

#56 Add Mosh to Dev Board
  assets/data/devs.json
  pubspec.lock
Labels: #30daysOfFlutter, 1 point

#58 52/ronealdenila
  assets/data/devs.json
Labels: #30daysOfFlutter, 1 point

#77 Add "Felix Jerome Dela Fuente" to Dev Board
  assets/data/devs.json
Labels: #30daysOfFlutter, 1 point

#62 [docs] add template for feature request | closes #44
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: #30daysOfFlutter, 1 point, documentation

#79 Add "Charles Louise Magno" to Dev Board
  README.md
Labels: #30daysOfFlutter, 1 point

#301 Add Felix Jerome Dela Fuente details
  assets/data/devs.json
Labels: #30daysOfFlutter, 1 point

#355 Add Jaymon Rivera details
  assets/data/devs.json
Labels: #30daysOfFlutter, 1 point

#353 Add Portia Bumanlag Details
  assets/data/devs.json
Labels: #30daysOfFlutter, 1 point

#302 Refactor search functionality
  lib/core/datasource/devs_datasource.dart
  lib/core/datasource/local/devs_local_datasource.dart
  lib/core/datasource/memory/devs_memory_datasource.dart
  lib/core/repositories/devs_repository.dart
  lib/core/widgets/components/search_bar.dart
  lib/features/dashboard/dashboard_model.dart
  lib/features/dashboard/dashboard_page.dart
  lib/features/devboard/devboard_model.dart
  lib/features/devboard/devboard_page.dart
  lib/features/devboard/devs/devs_list.dart
  lib/main.dart
  lib/utils/utils.dart
  pubspec.yaml
Labels: #30daysOfFlutter, 3 points

#291 Add John Lester D. Necesito details
  assets/data/devs.json
Labels: #30daysOfFlutter, 1 point

#343 Add Paul Cedo details to Dev board
  assets/data/devs.json
Labels: #30daysOfFlutter, 1 point
